# Stage 1: Build the Angular app
FROM node:16 as build
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install
COPY . .
RUN npm run build --prod

# Stage 2: Serve the app using Nginx
FROM nginx:1.19.2-alpine
COPY --from=build /app/dist/<your-app-name> /usr/share/nginx/html
COPY ./nginx-custom.conf /etc/nginx/conf.d/default.conf